spring:
  application:
    name: springboot2-nacos-config
#  cloud:
#    gateway:
#      enabled: true
#      routes:
#      - id: mdc-mvc-demo
#        uri: http://localhost:8081
#        predicates:
#        - Path=/mdc-mvc-demo/**
#        filters:
#        - StripPrefix= 1
server:
  servlet:
    context-path: /spring-gateway-demo
  port: 8082
nacos:
  config:
    server-addr: 127.0.0.1:8848

